apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: yournamespace
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: hello-world
spec:
  # ingressClassName: traefik
  rules:
    - host: hello.ef09bf4a-c942-4d17-a2cf-fd0163ae9a02.k8s.civo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: yournamespace
  labels:
    app: hello-world
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: yournamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: civo/docker-hello-world:latest
          ports:
            - containerPort: 5000


